modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/SirEdvin/ProgressivePeripherals/issues"
[[mods]]
modId="progressiveperipherals"
version="${file.jarVersion}"
displayName="Progressive Peripherals"
displayURL="https://github.com/SirEdvin/ProgressivePeripherals"
logoFile="pack.png"
authors="SirEdvin"
description='''
Progressive Peripherals is a mod that adds many useful extensions for Advanced Peripherals automata core system.
You can operate XP, perform enchantments, smithing recipes and much more.
In addition to automata core system expansion, you can find many useful peripherals, like reality forger, etc.
'''
[[dependencies.progressiveperipherals]]
    modId = "forge"
    mandatory = true
    versionRange = "[36.0.46,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.progressiveperipherals]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.5,1.17)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.progressiveperipherals]]
    modId = "computercraft"
    mandatory = true
    versionRange = "[1.98.0,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.progressiveperipherals]]
    modId = "advancedperipherals"
    mandatory = true
    versionRange = "[0.7.1r,)"
    ordering = "NONE"
    side = "BOTH"